#!/bin/bash

set -e

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
platform=`uname -a | awk '{print tolower($1)}'`
arch=`uname -m`
url="https://github.com/eboost-dev/eboost-dev/releases/download"
tag="v2.0"

tarball_name="eboost-linux64.tar.gz"
binary_url="${url}/${tag}/${tarball_name}"

download_bitcoind() {

    cd "${root_dir}/bin"

    echo "Downloading eBoost: ${binary_url}"

    is_curl=true
    if hash curl 2>/dev/null; then
        curl --fail -I $binary_url >/dev/null 2>&1
    else
        is_curl=false
        wget --server-response --spider $binary_url >/dev/null 2>&1
    fi

    if test $? -eq 0; then
        if [ "${is_curl}" = true ]; then
            curl -L $binary_url > $tarball_name
        else
            wget $binary_url
        fi
        if test -e "${tarball_name}"; then
            echo "Unpacking bitcoin distribution"
            tar -xvzf $tarball_name
            if test $? -eq 0; then

		ln -sf "eboost-linux64/./eboostd"
                return;
            fi
        fi
    fi
    echo "Bitcoin binary distribution could not be downloaded"
    exit -1
}

verify_download() {
   exit 0
}

download=1
verify=0

if [ "${SKIP_BITCOIN_DOWNLOAD}" = 1 ]; then
    download=0;
fi

if [ "${VERIFY_BITCOIN_DOWNLOAD}" = 1 ]; then
    verify=1;
fi

while [ -n "$1" ]; do
  param="$1"
  value="$2"

  case $param in
    --skip-bitcoin-download)
          download=0
          ;;
    --verify-bitcoin-download)
          verify=1
          ;;
  esac
  shift
done

if [ "${download}" = 1 ]; then
    download_bitcoind
fi

if [ "${verify}" = 1 ]; then
    verify_download
fi

exit 0
